config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/auth/github/callback', to: 'sessions#github'
  delete '/sign_out', to: 'sessions#destroy', as: :signout
  post '/webhooks/github', to: 'webhooks#github'
  get '/sign_up' => 'users#new', as: 'user_sign_up'
  get '/confirm_email/:token' => 'email_confirmations#confirm', as: 'confirm_email'
  resources :users
  resources :teams do
    resources :projects do
      resource :project_settings, only: %i(edit update), path: :settings

      resources :releases, only: %i(index edit update)
    end
  end
  resource :dashboard, only: %i(show)
  root 'home#index'
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :team_id }

  belongs_to :team
  has_many :releases
  has_one :settings, class_name: 'ProjectSetting', dependent: :destroy

  after_create :create_settings

  private

  def create_settings
    ProjectSetting.create!(project: self)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource :team
  load_and_authorize_resource

  def index
    @projects = @team.projects
  end

  def new
    @project = @team.projects.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = t('shared.created', resource: Project.model_name.human)
      redirect_to team_project_path(@team, @project)
    else
      flash[:error] = t('shared.not_created', resource: Project.model_name.human)
      render :new
    end
  end

  def update
    @project.update(project_params)
    if @project.save
      flash[:notice] = t('shared.updated', resource: Project.model_name.human)
      redirect_to team_project_path(@team, @project)
    else
      flash[:error] = t('shared.not_updated', resource: Project.model_name.human)
      render :edit
    end
  end

  def destroy
    if @project.destroy
      flash[:notice] = t('shared.deleted', resource: Project.model_name.human)
      redirect_to team_projects_path(@team)
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :team_id)
  end

end

app/views/projects/_form.html.erb
<%= simple_form_for project, url: url do |project| %>
  <%= project.input :name %>
  <%= project.association :team %>
  <%= project.button :submit %>
<% end %>
<br/>
<%= link_to I18n.t('back'), team_projects_path(team), class: 'btn-no-underline' %>

app/views/projects/edit.html.erb
<div class="simple-form">
  <div class="container">
    <h2><%= I18n.t('shared.edit_resource', resource: Project.model_name.human) %></h2>
    <%= render 'form', url: team_project_path, project: @project, team: @team %>
  </div>
</div>

app/views/projects/index.html.erb
<%= link_to t('back'), team_path(@team), class: 'btn-no-underline' %>
<h1><%= I18n.t('project.title') %></h1>
<table class="table">
  <thead>
  <tr>
    <th> <%= Project.human_attribute_name(:name) %> </th>
    <th> <%= I18n.t('shared.actions') %> </th>
  </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td> <%= project.name %> </td>
        <td>
          <%= link_to I18n.t('shared.show', resource: Project.model_name.human),
                      team_project_path(project.team, project) %>
          <% if can? :edit, project %>
            <%= link_to I18n.t('shared.edit', resource: Project.model_name.human),
                        edit_team_project_path(project.team, project) %>
          <% end %>
          <% if can? :settings, project %>
            <%= link_to Project.human_attribute_name(:settings),
                        edit_team_project_project_settings_path(project.team, project) %>
          <% end %>
          <% if can? :destroy, project %>
            <%= link_to I18n.t('shared.delete', resource: Project.model_name.human),
                        team_project_path(project.team, project),
                        method: :delete,
                        data: { confirm: I18n.t('shared.confirm', resource: Project.model_name.human) } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table><br/>
<% if can? :create, Project %>
  <%= link_to I18n.t('shared.create', resource: Project.model_name.human),
              new_team_project_path(@team),
              class: 'btn-no-underline' %>
<% end %>

app/views/projects/new.html.erb
<div class="simple-form">
  <div class="container">
    <h2 class="title"><%= I18n.t('shared.create', resource: Project.model_name.human) %></h2>
    <%= render 'form', url: team_projects_path, project: @project, team: @team %>
  </div>
</div>

app/views/projects/show.html.erb
<h2><%= t('shared.show_resource', resource: Project.model_name.human) %></h2>
<%= link_to t('back'),
            team_projects_path(@team),
            class: 'btn-no-underline' %>
<table class="table">
  <thead>
  <tr>
    <th><%= Project.human_attribute_name(:name) %></th>
    <th><%= Project.human_attribute_name(:team_id) %></th>
    <th><%= t('release.list') %></th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @project.name %></td>
    <td><%= @project.team.name %></td>
    <td><%= link_to t('release.list'), team_project_releases_path(@team, @project) %></td>
  </tr>
  </tbody>
</table>