config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/auth/github/callback', to: 'sessions#github'
  delete '/sign_out', to: 'sessions#destroy', as: :signout
  post '/webhooks/github', to: 'webhooks#github'
  get '/sign_up' => 'users#new', as: 'user_sign_up'
  get '/confirm_email/:token' => 'email_confirmations#confirm', as: 'confirm_email'
  resources :users
  resources :teams do
    resources :projects do
      resource :project_settings, only: %i(edit update), path: :settings

      resources :releases, only: %i(index edit update)
    end
  end
  resource :dashboard, only: %i(show)
  root 'home#index'
end

app/models/project_setting.rb
class ProjectSetting < ApplicationRecord
  belongs_to :project
  attr_encrypted :jira_api_token,
                 key: Global.jira.encryption_key,
                 mode: :per_attribute_iv
  validates_format_of :jira_username,
                      with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, if: :jira_username
  validate :urls

  private

  def urls
    return unless git_repo_url && jira_site

    errors.add(:git_repo_url, 'invalid url') if git_repo_url && !valid_url?(git_repo_url)
    errors.add(:jira_site, 'invalid url') if jira_site && !valid_url?(jira_site)
  end

  def valid_url?(url)
    uri = URI.parse(url)
    uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    false
  end
end

app/controllers/project_settings_controller.rb
class ProjectSettingsController < ApplicationController
  load_and_authorize_resource :team
  load_and_authorize_resource :project
  before_action :find_setting
  authorize_resource

  def edit; end

  def update
    if @project_setting.update(settings_params)
      redirect_to edit_team_project_project_settings_path(@team, @project),
                  notice: t('shared.updated', resource: ProjectSetting.model_name.human)
    else
      render :edit
    end
  end

  private

  def find_setting
    @project_setting = @project&.settings
    unless @project_setting
      flash[:error] = t('shared.not_found', resource: Project.model_name.human)
      redirect_to team_projects_path(@team)
    end
  end

  def settings_params
    params.
      require(:project_setting).
      permit(:project_id, :git_repo_url, :git_repo_identifier, :git_release_branch,
             :git_webhook_url, :jira_username, :jira_api_token,
             :jira_site, :jira_project_slug)
  end
end

app/views/project_settings/_form.html.erb
<%= simple_form_for(project_setting, url: team_project_project_settings_path(team, project)) do |f| %>
  <%= f.input :git_repo_url %>
  <%= f.input :git_repo_identifier %>
  <%= f.input :git_release_branch %>
  <%= f.input :git_webhook_url %>
  <%= f.input :jira_username %>
  <%= f.input :jira_api_token %>
  <%= f.input :jira_site %>
  <%= f.input :jira_project_slug %>
  <%= f.button :submit %>
<% end %>
<br>
<%= link_to I18n.t('back'), team_project_path(team, project), class: 'btn-no-underline' %>

app/views/project_settings/edit.html.erb
<div class="simple-form">
  <div class="container">
    <h4><%= t('shared.edit_resource', resource: ProjectSetting.model_name.human) %></h4><br/>
    <%= render 'form', project_setting: @project_setting, project: @project, team: @team  %>
  </div>
</div>